import {expect,test} from 'vitest';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync('public/playmint-sdk.js','utf8');
function sdk(enabled=true){let placement:Record<string,any>|undefined;const window:any={addEventListener(){},__PLAYMINT_CONFIG:{enabled,rewarded:true,startup:true,midgame:true,intervalSeconds:300},adBreak:(o:Record<string,any>)=>{placement=o;}};const context={window,parent:window,document:{visibilityState:'visible'},setTimeout,clearTimeout,setInterval:()=>1,clearInterval:()=>{}};vm.runInNewContext(source,context);return {window,get placement(){return placement;}};}
test('pending provider approval never displays ads or grants rewards',async()=>{const s=sdk(false);const result=await s.window.Playmint.requestReward('revive');expect(result.completed).toBe(false);expect(s.placement).toBeUndefined();expect(s.window.Playmint.purchases.available).toBe(false);});
test('missing pause hookup skips midgame; completed reward pauses and resumes exactly once',async()=>{const s=sdk();expect((await s.window.Playmint.gameBreak()).reason).toBe('pause_not_connected');let paused=0,resumed=0;s.window.Playmint.init({pause:()=>paused++,resume:()=>resumed++});const reward=s.window.Playmint.requestReward('double_damage');s.placement!.beforeAd();s.placement!.adViewed();s.placement!.afterAd();s.placement!.adBreakDone({breakStatus:'viewed'});expect((await reward).completed).toBe(true);expect(paused).toBe(1);expect(resumed).toBe(1);expect((await s.window.Playmint.gameBreak()).reason).toBe('frequency_capped');});
test('cancelled and no-fill ads never grant a reward',async()=>{for(const status of ['dismissed','noAdPreloaded','error']){const s=sdk();s.window.Playmint.init({pause(){},resume(){}});const result=s.window.Playmint.requestReward('extra_hp');if(status==='dismissed')s.placement!.adDismissed();s.placement!.adBreakDone({breakStatus:status});expect((await result).completed).toBe(false);}});
test('a developer loading the auto-injected SDK again does not lose pause and resume hooks',async()=>{const s=sdk();let resumed=0;s.window.Playmint.init({pause(){},resume(){resumed++;}});vm.runInNewContext(source,{window:s.window,parent:s.window,document:{visibilityState:'visible'},setTimeout,clearTimeout,setInterval:()=>1,clearInterval:()=>{}});const result=s.window.Playmint.requestReward('revive');s.placement!.beforeAd();s.placement!.adViewed();s.placement!.adBreakDone({breakStatus:'viewed'});expect((await result).completed).toBe(true);expect(resumed).toBe(1);});
