import "server-only";
import fs from "node:fs/promises";
import {createReadStream,createWriteStream} from "node:fs";
import {Readable,Transform} from "node:stream";
import {pipeline} from "node:stream/promises";
import path from "node:path";
import {paths} from "@/lib/env";
import {newId} from "@/lib/ids";
export const CHUNK_BYTES=8*1024*1024;
export const MAX_ARCHIVE_BYTES=2*1024*1024*1024;
const TTL=24*3600_000;
export type UploadRecord={id:string;owner:string;filename:string;total:number;received:number;next:number;createdAt:number;updatedAt:number;status:"uploading"|"ready"|"queued"|"processing"|"done"|"failed";job?:{gameId:string;isNew:boolean;reused?:boolean;locale:"tr"|"az"|"en";changelog:string;maxZipMb:number};pid?:number;versionId?:string;error?:string};
export class UploadError extends Error{constructor(public code:string,public status=400){super(code);}}
const root=(id:string)=>{if(!/^[a-z0-9]{20}$/.test(id))throw new UploadError("not_found",404);return path.join(paths.uploads(),id);};
export const archivePath=(id:string)=>path.join(root(id),"archive.zip");
export function processAlive(pid?:number){if(!pid)return false;try{process.kill(pid,0);return true;}catch{return false;}}
export async function writeUpload(record:UploadRecord){record.updatedAt=Date.now();const file=path.join(root(record.id),"state.json"),tmp=file+`.${newId()}.tmp`;await fs.writeFile(tmp,JSON.stringify(record),{mode:0o600});await fs.rename(tmp,file);}
export async function getUpload(id:string,owner:string){let record:UploadRecord;try{record=JSON.parse(await fs.readFile(path.join(root(id),"state.json"),"utf8"));}catch(e){if(e instanceof UploadError)throw e;throw new UploadError("not_found",404);}if(record.owner!==owner)throw new UploadError("not_found",404);if(record.updatedAt+TTL<Date.now())throw new UploadError("expired",410);return record;}
export async function uploadLock<T>(id:string,fn:()=>Promise<T>):Promise<T>{const lock=path.join(root(id),"lock");let fd;try{fd=await fs.open(lock,"wx",0o600);}catch{let stale=false;try{const data=JSON.parse(await fs.readFile(lock,"utf8"));stale=!processAlive(data.pid)||(await fs.stat(lock)).mtimeMs<Date.now()-10*60_000;}catch{try{stale=(await fs.stat(lock)).mtimeMs<Date.now()-10*60_000;}catch{}}if(!stale)throw new UploadError("busy",409);await fs.rm(lock,{force:true});try{fd=await fs.open(lock,"wx",0o600);}catch{throw new UploadError("busy",409);}}await fd.writeFile(JSON.stringify({pid:process.pid}));const tick=setInterval(()=>fs.utimes(lock,new Date(),new Date()).catch(()=>{}),30000);try{return await fn();}finally{clearInterval(tick);await fd.close();await fs.rm(lock,{force:true});}}
export async function beginUpload(owner:string,filename:string,total:number,maximum:number){if(!Number.isSafeInteger(total)||total<22||total>Math.min(maximum,MAX_ARCHIVE_BYTES))throw new UploadError("file_too_big",413);if(!filename.toLowerCase().endsWith(".zip"))throw new UploadError("zip_invalid");await fs.mkdir(paths.uploads(),{recursive:true});let active=0;for(const entry of await fs.readdir(paths.uploads(),{withFileTypes:true})){if(!entry.isDirectory()||!/^[a-z0-9]{20}$/.test(entry.name))continue;try{const s:UploadRecord=JSON.parse(await fs.readFile(path.join(paths.uploads(),entry.name,"state.json"),"utf8"));if(s.updatedAt+TTL<Date.now()&&!processAlive(s.pid)){await fs.rm(path.join(paths.uploads(),entry.name),{recursive:true,force:true});continue;}if(s.owner===owner&&!['done','failed'].includes(s.status))active++;}catch{}}
 if(active>=2)throw new UploadError("too_many_uploads",429);const disk=await fs.statfs(paths.uploads());if(disk.bavail*disk.bsize<total*2+2*1024**3)throw new UploadError("storage_unavailable",503);const id=newId();await fs.mkdir(root(id),{mode:0o700});const record:UploadRecord={id,owner,filename:path.basename(filename).slice(0,200),total,received:0,next:0,createdAt:Date.now(),updatedAt:Date.now(),status:"uploading"};await fs.writeFile(archivePath(id),Buffer.alloc(0),{mode:0o600});await writeUpload(record);return record;}
export async function appendChunk(id:string,owner:string,index:number,body:ReadableStream<Uint8Array>|null){if(!body||!Number.isSafeInteger(index)||index<0)throw new UploadError("bad_chunk");return uploadLock(id,async()=>{const record=await getUpload(id,owner);if(index<record.next)return record;if(record.status!=="uploading"||index!==record.next)throw new UploadError("bad_chunk");const expected=Math.min(CHUNK_BYTES,record.total-record.received),temp=path.join(root(id),"part.tmp");let bytes=0;const limiter=new Transform({transform(chunk:Buffer,_enc,cb){bytes+=chunk.length;cb(bytes>expected?new UploadError("bad_chunk"):null,chunk);}});try{await pipeline(Readable.fromWeb(body as Parameters<typeof Readable.fromWeb>[0]),limiter,createWriteStream(temp,{mode:0o600}));if(bytes!==expected)throw new UploadError("bad_chunk");await fs.truncate(archivePath(id),record.received);await pipeline(createReadStream(temp),createWriteStream(archivePath(id),{flags:"a",mode:0o600}));record.received+=bytes;record.next++;if(record.received===record.total)record.status="ready";await writeUpload(record);return record;}catch(e){await fs.truncate(archivePath(id),record.received).catch(()=>{});throw e;}finally{await fs.rm(temp,{force:true});}});}
export async function queueUpload(id:string,owner:string,job:NonNullable<UploadRecord["job"]>){return uploadLock(id,async()=>{const record=await getUpload(id,owner);if(record.status!=="ready")throw new UploadError("not_ready",409);record.job=job;record.status="queued";await writeUpload(record);return record;});}
export async function removeUploadArchive(id:string){await fs.rm(archivePath(id),{force:true});}

export async function cancelUpload(id:string,owner:string){return uploadLock(id,async()=>{const r=await getUpload(id,owner);if(r.status==='queued'||r.status==='processing'||r.status==='done')throw new UploadError('busy',409);r.status='failed';r.error='canceled';await removeUploadArchive(id);await writeUpload(r);});}
