import {test,expect} from '@playwright/test';
import path from 'node:path';
for(const width of [375,768,1440])test(`public pages fit ${width}px and only approved games appear`,async({page})=>{await page.setViewportSize({width,height:1000});for(const route of ['/tr','/tr/games','/tr/register','/az/legal/privacy','/en/report']){await page.goto(route);await expect(page.locator('h1').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}await page.goto('/tr');const links=await page.locator('.game-tile').evaluateAll(els=>els.map(el=>el.getAttribute('href')));expect(new Set(links).size).toBe(links.length);const regular=page.locator('.game-tile:not(.portal-spotlight) .game-cover');if(await regular.count()){const r=await regular.first().boundingBox();expect(Math.abs(r!.width-r!.height)).toBeLessThan(1);}const spotlight=page.locator('.portal-spotlight');if(await spotlight.count())await expect(spotlight).toBeVisible();});
for(const width of [375,1440])test(`language flags navigate at ${width}px without losing the catalogue query`,async({page})=>{await page.setViewportSize({width,height:812});await page.goto('/tr/games?sort=new');await page.locator('.language-trigger').click();await page.locator('.language-options button[lang=en]').click();await expect(page).toHaveURL(/\/en\/games\?sort=new/);await expect(page.locator('.language-trigger img')).toHaveAttribute('src','/flags/en.svg?v=2');});
test('mobile immersive player can exit without reloading the game',async({page})=>{await page.setViewportSize({width:375,height:812});await page.goto('/tr');const link=page.locator('.game-tile').first();test.skip(await link.count()===0,'No published games available');await link.click();await page.waitForURL(/\/g\//);await expect(page.locator('.player-stage')).toBeVisible();const play=page.getByRole('button',{name:'Oyna',exact:true});await page.route('**/api/play/start',async route=>route.fulfill({json:{url:'about:blank',token:null}}));await play.click();const frame=page.locator('iframe[title=game]');await expect(frame).toBeVisible();await frame.evaluate(el=>(el as HTMLElement).dataset.qaFrame='preserved');const close=page.getByRole('button',{name:'Tam ekrandan çık',exact:true});await expect(close).toBeVisible();await close.click();await expect(page.locator('.is-immersive')).toHaveCount(0);await expect(frame).toHaveAttribute('data-qa-frame','preserved');expect(await page.evaluate(()=>document.body.style.overflow)).not.toBe('hidden');});
test('home and contact form have no serious or critical accessibility violations',async({page})=>{for(const route of ['/tr','/en/report']){await page.goto(route);await page.addScriptTag({path:path.resolve('node_modules/axe-core/axe.min.js')});const violations=await page.evaluate(async()=>{const a=(window as unknown as {axe:{run:()=>Promise<{violations:{id:string;impact:string;nodes:{target:string[]}[]}[]}>}}).axe;return (await a.run()).violations.filter(v=>['critical','serious'].includes(v.impact)).map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}));});expect(violations).toEqual([]);}});
for(const width of [375,1440])test(`catalogue visual regression ${width}px`,async({page})=>{await page.route('**/pagead2.googlesyndication.com/**',route=>route.abort());await page.setViewportSize({width,height:1000});await page.goto('/tr');await page.evaluate(()=>document.fonts.ready);await expect(page).toHaveScreenshot(`home-${width}.png`,{animations:'disabled',mask:[page.locator('.game-tile > div:last-child > div:last-child')],maxDiffPixelRatio:0.01});});

test('mobile portal search and opening game covers navigate correctly',async({page})=>{await page.setViewportSize({width:375,height:812});await page.goto('/tr');await page.locator('.portal-search input').fill('Pocket');await page.locator('.portal-search input').press('Enter');await expect(page).toHaveURL(/\/tr\/games\?q=Pocket/);await expect(page.locator('.game-tile').first()).toContainText('Pocket');await page.goto('/tr');await expect(page.locator('.discovery-grid')).toHaveCount(0);await expect(page.locator('.portal-opening-games .game-tile')).toHaveCount(4);await page.locator('.portal-opening-games .game-tile').first().click();await expect(page).toHaveURL(/\/tr\/g\//);await expect(page.locator('.player-stage')).toBeVisible();});
