const scene=new THREE.Scene();scene.background=new THREE.Color('#a9e9ec');scene.fog=new THREE.Fog('#a9e9ec',45,145);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,180);camera.position.set(0,5.3,11);camera.lookAt(0,1,-17);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.querySelector('#world').append(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x537b84,2));const sun=new THREE.DirectionalLight(0xffefcb,2);sun.position.set(12,28,18);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-22;sun.shadow.camera.right=22;sun.shadow.camera.top=30;sun.shadow.camera.bottom=-30;scene.add(sun);
const mats={grass:new THREE.MeshStandardMaterial({color:0x86c7a4}),track:new THREE.MeshStandardMaterial({color:0x667b92}),rail:new THREE.MeshStandardMaterial({color:0xb5d4dc,metalness:.5,roughness:.45}),fox:new THREE.MeshStandardMaterial({color:0xf49f56,roughness:.7}),cream:new THREE.MeshStandardMaterial({color:0xffe8cb}),hoodie:new THREE.MeshStandardMaterial({color:0x8063d9}),dark:new THREE.MeshStandardMaterial({color:0x303849}),gold:new THREE.MeshStandardMaterial({color:0xffcc47,metalness:.65,roughness:.25})};
function box(w,h,d,mat,x,y,z,parent=scene){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;parent.add(m);return m}
function ball(r,mat,x,y,z,parent=scene){const m=new THREE.Mesh(new THREE.SphereGeometry(r,16,12),mat);m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m}
box(200,.5,300,mats.grass,0,-.45,-120);box(9,.2,280,mats.track,0,-.1,-120);for(let lane=-1;lane<=1;lane++)for(const x of [-.8,.8])box(.09,.12,280,mats.rail,lane*2.65+x,.08,-120);
const scenery=[];for(let z=-145;z<20;z+=7){for(const sign of [-1,1]){const color=new THREE.MeshStandardMaterial({color:[0xffad96,0xa6b5ed,0xffd998,0x90c9c3][Math.abs(Math.floor(z/7))%4]});const h=4+Math.random()*9;const building=box(4,h,5,color,sign*(9+Math.random()*4),h/2,z);for(let y=1;y<h;y+=2)for(let k=-1;k<=1;k++)box(.65,.9,.06,mats.cream,sign*(9)+k, y,z+2.55,scene);scenery.push(building);const trunk=box(.3,2,.3,mats.dark,sign*5.7,1,z+1);const crown=ball(1.1,new THREE.MeshStandardMaterial({color:0x4aa68b}),sign*5.7,2.8,z+1);scenery.push(trunk,crown)}}
const sleepers=[];for(let z=-140;z<15;z+=2.8)sleepers.push(box(8.2,.13,.22,mats.dark,0,.02,z));
const fox=new THREE.Group();scene.add(fox);fox.position.set(0,0,3);const torso=box(.85,1,.65,mats.hoodie,0,1.08,0,fox);const head=ball(.58,mats.fox,0,1.98,0,fox);ball(.4,mats.cream,0,1.79,.37,fox);ball(.09,mats.dark,0,1.93,.68,fox);for(const side of [-1,1]){const ear=new THREE.Mesh(new THREE.ConeGeometry(.24,.62,3),mats.fox);ear.position.set(side*.36,2.53,0);ear.rotation.z=side*-.2;fox.add(ear);ball(.08,mats.dark,side*.24,2.06,.47,fox)}const legs=[box(.27,.65,.3,mats.dark,-.23,.35,0,fox),box(.27,.65,.3,mats.dark,.23,.35,0,fox)];const arms=[box(.22,.73,.22,mats.fox,-.56,1.12,0,fox),box(.22,.73,.22,mats.fox,.56,1.12,0,fox)];const tail=ball(.34,mats.fox,0,.8,-.72,fox);tail.scale.set(1,1,2);ball(.23,mats.cream,0,.8,-1.2,fox);
let playing=false,ended=false,lane=0,y=0,vy=0,slide=0,elapsed=0,coins=0,distance=0,hp=3,immune=0,timer=0;const actors=[];const overlay=document.querySelector('#overlay'),hud=document.querySelector('#stats');
function obstacle(){const l=Math.floor(Math.random()*3)-1;const type=Math.random()<.45?'train':Math.random()<.55?'barrier':'gate';const group=new THREE.Group();scene.add(group);group.position.set(l*2.65,0,-115);if(type==='train'){const mat=new THREE.MeshStandardMaterial({color:[0x49bdcf,0xfcaa77,0x8d80db][l+1]});box(2.1,2.9,8,mat,0,1.5,0,group);box(1.7,.65,.06,mats.dark,0,2.2,4.05,group);for(const x of [-.65,.65])ball(.1,mats.cream,x,.8,4.12,group)}else if(type==='barrier'){box(2.2,.75,.4,new THREE.MeshStandardMaterial({color:0xf07773}),0,.42,0,group);box(1.9,.13,.45,mats.cream,0,.62,0,group)}else{for(const x of [-1.02,1.02])box(.13,2.8,.2,mats.dark,x,1.4,0,group);box(2.2,.6,.4,new THREE.MeshStandardMaterial({color:0xe8b14a}),0,2.1,0,group)}actors.push({group,lane:l,type,hit:false});for(let i=0;i<8;i++){const coin=new THREE.Mesh(new THREE.TorusGeometry(.26,.08,7,16),mats.gold);coin.position.set(((l+2)%3-1)*2.65,1.15,-115-i*2.5);scene.add(coin);actors.push({group:coin,lane:(l+2)%3-1,type:'coin'})}}
function act(action){if(!playing)return;if(action==='left')lane=Math.max(-1,lane-1);if(action==='right')lane=Math.min(1,lane+1);if(action==='jump'&&y===0&&slide<=0)vy=7;if(action==='slide'&&y<.1)slide=1.05}
addEventListener('keydown',e=>{const map={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'jump',w:'jump',' ':'jump',ArrowDown:'slide',s:'slide'};if(map[e.key]){e.preventDefault();act(map[e.key])}});document.querySelectorAll('[data-act]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();act(b.dataset.act)}));let gesture;renderer.domElement.addEventListener('pointerdown',e=>gesture=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!gesture)return;const dx=e.clientX-gesture[0],dy=e.clientY-gesture[1];if(Math.max(Math.abs(dx),Math.abs(dy))>20)act(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy<0?'jump':'slide');else act('jump');gesture=null});
function reset(){for(const a of actors)scene.remove(a.group);actors.length=0;playing=true;ended=false;lane=0;y=vy=slide=elapsed=coins=distance=timer=0;hp=3;immune=2;overlay.hidden=true;document.querySelector('#controls').hidden=false;for(let i=0;i<3;i++){obstacle();actors.slice(i*9).forEach(a=>a.group.position.z-=i*28)}}
document.querySelector('#start').onclick=reset;document.querySelector('#pause').onclick=()=>{if(ended||!overlay.hidden)return;playing=!playing;document.querySelector('#pause').textContent=playing?'Ⅱ':'▶'};
let prev=performance.now();function loop(now){requestAnimationFrame(loop);const dt=Math.min((now-prev)/1000,.035);prev=now;const speed=playing?Math.min(30,16+elapsed*.07):0;if(playing){elapsed+=dt;distance+=speed*dt;immune=Math.max(0,immune-dt);slide=Math.max(0,slide-dt);y=Math.max(0,y+vy*dt);if(y>0||vy>0)vy-=17*dt;else vy=0;fox.position.x+=(lane*2.65-fox.position.x)*Math.min(1,dt*15);fox.position.y=y;fox.scale.y=slide>0?.48:1;fox.rotation.z=Math.sin(elapsed*15)*.035;legs.forEach((m,i)=>m.rotation.x=Math.sin(elapsed*14+i*Math.PI)*.8);arms.forEach((m,i)=>m.rotation.x=-Math.sin(elapsed*14+i*Math.PI)*.7);fox.visible=immune<=0||Math.sin(elapsed*35)>-.1;timer+=dt;if(timer>1.9){timer=0;obstacle()}for(let i=actors.length-1;i>=0;i--){const a=actors[i];a.group.position.z+=speed*dt;if(a.type==='coin')a.group.rotation.y+=dt*3;if(Math.abs(a.group.position.z-3)<(a.type==='train'?4:1)&&Math.abs(a.group.position.x-fox.position.x)<.9){if(a.type==='coin'){coins++;scene.remove(a.group);actors.splice(i,1);continue}if(!a.hit&&immune===0&&!(a.type==='barrier'&&y>.95)&&!(a.type==='gate'&&slide>0)){a.hit=true;hp--;immune=1.8;if(hp<=0){playing=false;ended=true;overlay.hidden=false;document.querySelector('#title').textContent='Güzel koşuydu!';document.querySelector('#subtitle').textContent=Math.floor(distance)+' metre · '+coins+' altın';document.querySelector('#start').textContent='Yeniden koş'}}}if(a.group.position.z>22){scene.remove(a.group);actors.splice(i,1)}}for(const m of sleepers){m.position.z+=speed*dt;if(m.position.z>15)m.position.z-=155}hud.textContent=Math.floor(distance)+' m  ·  '+coins+' altın  ·  '+hp+' can'}else if(!ended){fox.rotation.y=Math.sin(now*.0005)*.15;fox.position.y=Math.sin(now*.003)*.06}renderer.render(scene,camera)}requestAnimationFrame(loop);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){playing=false;document.querySelector('#pause').textContent='▶'}});window.__gameQA=()=>({playing,lane,distance,coins,hp,actors:actors.length});
