import Link from "next/link";
import {and,eq,desc} from "drizzle-orm";
import {resolveLocale} from "@/lib/i18n";
import {requireUser} from "@/lib/auth";
import {db,schema} from "@/lib/db";
import {date,money} from "@/lib/format";
import {StudioHeading,StudioEmpty} from "@/components/Studio";
import {studioCopy} from "@/lib/studio-copy";
import {cancelPlayerSubscription} from "../settings/actions";
export default async function Subscriptions({params}:PageProps<"/[locale]/me/subscriptions">){const {locale}=await resolveLocale(params);const user=await requireUser(locale),en=locale==="en",az=locale==="az",c=studioCopy(locale);const rows=await db.select({sub:schema.subscriptions,game:schema.games.title,slug:schema.games.slug}).from(schema.subscriptions).innerJoin(schema.games,eq(schema.games.id,schema.subscriptions.gameId)).where(and(eq(schema.subscriptions.userId,user.id),eq(schema.games.isDemo,false))).orderBy(desc(schema.subscriptions.createdAt));return <div className="space-y-7"><StudioHeading eyebrow="SUPPORT THE GAMES YOU LOVE" title={en?"My subscriptions":az?"Abunəliklərim":"Aboneliklerim"} accent="violet" description={en?"Your subscriptions only cover the games they belong to.":az?"Abunəliklərin yalnız aid olduğu oyun üçün keçərlidir.":"Aboneliklerin yalnızca ait olduğu oyunda geçerlidir."}/>{rows.length?<div className="grid gap-5 lg:grid-cols-2">{rows.map(({sub:s,game,slug})=>{const active=s.status==="active"&&s.currentPeriodEnd>new Date();return <article className="plan-card" key={s.id}><div className="plan-card-top"><h2>{game}</h2><p className="mt-2 text-sm">{money(s.priceCents,s.currency,locale)} / {en?"month":locale === "az" ? "ay" : "ay"}</p></div><div className="p-6 space-y-3"><span className="badge bg-surface-2">{active?c.active:c.expired}{s.provider==="mock"?` · ${c.test}`:""}</span><p className="text-xs text-muted">{en?"Period end":az?"Dövrün sonu":"Dönem sonu"}: {date(s.currentPeriodEnd,locale)}</p>{s.cancelAtPeriodEnd&&<p className="text-xs text-amber">{en?"Ends after this period":az?"Dövr sonunda bitir":"Dönem sonunda bitecek"}</p>}<div className="flex gap-3 flex-wrap"><Link className="btn btn-ghost btn-sm" href={`/${locale}/g/${slug}`}>{en?"View game":az?"Oyuna bax":"Oyunu gör"} ↗</Link>{active&&!s.cancelAtPeriodEnd&&<form action={cancelPlayerSubscription}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="subscriptionId" value={s.id}/><button className="btn btn-ghost btn-sm">{en?"Cancel renewal":az?"Yenilənməni ləğv et":"Yenilemeyi iptal et"}</button></form>}</div></div></article>;})}</div>:<StudioEmpty icon="plan" title={en?"No game subscription yet":az?"Hələ oyun abunəliyin yoxdur":"Henüz oyun aboneliğin yok"} text={en?"Explore games and find a creator you want to support.":az?"Oyunları kəşf et, dəstəkləmək istədiyin geliştiricini tap.":"Oyunları keşfet, desteklemek istediğin geliştiriciyi bul."} href={`/${locale}/games`} cta={en?"Explore games":az?"Oyunları kəşf et":"Oyunları keşfet"}/>}</div>;}
