import Link from "next/link";
import {and,eq} from "drizzle-orm";
import {resolveLocale} from "@/lib/i18n";
import {requireDeveloper} from "@/lib/auth";
import {db,schema} from "@/lib/db";
import {StudioHeading,StudioEmpty} from "@/components/Studio";
import {studioCopy} from "@/lib/studio-copy";
import {PlanForm} from "./PlanForm";
export default async function Plans({params}:PageProps<"/[locale]/dev/subscriptions">){const {locale}=await resolveLocale(params);const user=await requireDeveloper(locale),c=studioCopy(locale),en=locale==="en",az=locale==="az";const games=await db.select().from(schema.games).where(and(eq(schema.games.developerId,user.id),eq(schema.games.isDemo,false)));return <div className="space-y-7"><StudioHeading eyebrow="YOUR GAME · YOUR PRICE" title={c.plans} accent="violet" description={en?"Create a separate subscription offer for each of your games.":az?"Hər oyunun üçün ayrı abunəlik yarat.":"Her oyunun için ayrı bir abonelik planı oluştur."}/><section className="plan-summary flex flex-wrap justify-between gap-4"><div><strong className="text-xl">{games.filter(g=>g.subscriptionPriceCents>0).length} {en?"game plans":az?"oyun planı":"oyun planı"}</strong><p className="text-xs mt-2 max-w-lg leading-relaxed">{c.noPayments}</p></div><Link className="btn btn-ghost self-start" href={`/${locale}/dev/subscribers`}>{c.subscribers} →</Link></section><p className="text-xs text-muted">{en?"Price changes apply to new subscriptions. Each subscription covers only its own game.":az?"Qiymət dəyişiklikləri yeni abunəliklərə aiddir. Hər abunəlik yalnız öz oyununa keçərlidir.":"Fiyat değişiklikleri yeni abonelikler için uygulanır. Her abonelik yalnızca ait olduğu oyunda geçerlidir."}</p>{games.length?<div className="grid gap-5 xl:grid-cols-2">{games.map(g=><article className="plan-card" key={g.id}><div className="plan-card-top"><p className="studio-kicker">GAME SUBSCRIPTION</p><h2 className="mt-2">{g.title}</h2></div><PlanForm locale={locale} game={g}/></article>)}</div>:<StudioEmpty icon="plan" title={en?"A plan for your next game":az?"Oyunun üçün bir plan":"Oyununa özel bir plan"} text={en?"Upload a game first, then choose its monthly price and benefits.":az?"Əvvəl oyun yüklə, sonra aylıq qiymətini seç.":"Önce oyununu yükle, ardından aylık fiyatını ve abone avantajlarını belirle."} href={`/${locale}/dev/games/new`} cta={c.upload}/>}</div>;}
