"use client";
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {type VirusTotalReport} from '@/lib/virustotal-result';
export function VirusTotalPanel({versionId,initial,pending,locale}:{versionId:string;initial?:VirusTotalReport;pending:boolean;locale:string}){
 const [scan,setScan]=useState(initial);const router=useRouter();const en=locale==='en',az=locale==='az';
 useEffect(()=>{if(!pending||scan?.status==='completed')return;let active=true;const update=async()=>{try{await fetch(`/api/review/scan/${versionId}`,{method:'POST'});const res=await fetch(`/api/review/scan/${versionId}`,{cache:'no-store'});if(res.ok&&active){const data=await res.json();setScan(data.scan);if(data.scan?.status==='completed')router.refresh();}}catch{}};void update();const interval=setInterval(update,20000);return()=>{active=false;clearInterval(interval);};},[versionId,pending,scan?.status,router]);
 const labels={pending:en?'Waiting for scan':az?'Tarama gözlənilir':'Tarama bekleniyor',not_configured:en?'VirusTotal is not connected. Configure VIRUSTOTAL_API_KEY on the server.':az?'VirusTotal bağlı deyil. Serverdə VIRUSTOTAL_API_KEY təyin edilməlidir.':'VirusTotal bağlı değil. Sunucuda VIRUSTOTAL_API_KEY tanımlanmalı.',submitted:en?'VirusTotal is analyzing the playable output.':az?'VirusTotal oyun çıxışını yoxlayır.':'VirusTotal çalışır oyun çıktısını tarıyor.',completed:en?'Analysis completed':az?'Tarama tamamlandı':'Tarama tamamlandı',error:en?'Scan could not be completed':az?'Tarama tamamlanmadı':'Tarama tamamlanamadı',runtime_missing:en?'A playable build is required for scanning.':az?'Tarama üçün hazır oyun çıxışı lazımdır.':'Tarama için hazır oyun çıktısı gerekiyor.'};
 return <section className="card space-y-3 p-4 text-sm"><h2 className="font-display font-bold">VirusTotal · dist</h2><p className={scan?.status==='completed'?'text-mint':'text-amber'}>{labels[scan?.status??'pending']}</p>{scan?.error&&<p className="text-danger">{scan.error}</p>}{scan?.stats&&<><p><b>{scan.stats.malicious??0}</b> {en?'malicious':az?'zərərli':'zararlı'} · <b>{scan.stats.suspicious??0}</b> {en?'suspicious':az?'şübhəli':'şüpheli'} · <b>{scan.stats.undetected??0}</b> {en?'undetected':az?'aşkarlanmadı':'tespit yok'}</p><details><summary className="cursor-pointer">{en?'All result counts':'Tüm sonuç sayıları'}</summary><ul>{Object.entries(scan.stats).map(([k,v])=><li key={k}>{k}: {v}</li>)}</ul></details></>}{scan?.detections?.map((d,i)=><p className="rounded-lg bg-danger/10 p-2 text-danger" key={i}><b>{d.engine}</b>: {d.result} ({d.category})</p>)}{scan?.sha256&&<a className="block text-mint underline" href={`https://www.virustotal.com/gui/file/${scan.sha256}`} target="_blank" rel="noreferrer">{en?'Open VirusTotal report':'VirusTotal raporunu aç'} ↗</a>}<p className="text-xs text-muted">{en?'Only the playable output is scanned. No detections does not guarantee safety. Admin review is still required.':az?'Yalnız oyun çıxışı yoxlanılır. Aşkarlama olmaması təhlükəsizlik zəmanəti deyil. Admin yoxlaması davam edir.':'Yalnızca oyun çıktısı taranır. Tespit olmaması güvenlik garantisi değildir. Admin incelemesi de gereklidir.'}</p></section>;
}
