const {Pool}=require('pg'),{chromium,firefox}=require('@playwright/test'),crypto=require('crypto'),fs=require('fs/promises'),assert=require('assert');
const pool=new Pool({connectionString:process.env.DATABASE_URL}),base='https://playmint.tr',suffix=crypto.randomBytes(4).toString('hex'),ids=[crypto.randomBytes(10).toString('hex'),crypto.randomBytes(10).toString('hex')],tokens=[crypto.randomBytes(32).toString('base64url'),crypto.randomBytes(32).toString('base64url')];let browser;
(async()=>{try{
 await fs.mkdir('test-results/community',{recursive:true});
 for(let i=0;i<2;i++){await pool.query("insert into users(id,email,name,username,password_hash,role) values($1,$2,$3,$4,'disabled','player')",[ids[i],`qa-${ids[i]}@qa.invalid`,i?'Follows QA Bob':'Follows QA Alice',`qa_${i?'bob':'alice'}_${suffix}`]);await pool.query("insert into sessions(id,user_id,expires_at) values($1,$2,now()+interval '1 hour')",[crypto.createHash('sha256').update(tokens[i]).digest('hex'),ids[i]]);}
 browser=await chromium.launch({headless:true,executablePath:process.env.PLAYMINT_CHROMIUM_PATH||'/root/.cache/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']});
 const ctx=await browser.newContext({viewport:{width:375,height:812},hasTouch:true});await ctx.addCookies([{name:'__Host-pm_session',value:tokens[0],domain:'playmint.tr',path:'/',secure:true,httpOnly:true,sameSite:'Lax'}]);const guest=await browser.newContext();for(let attempt=0;attempt<20;attempt++){const health=await guest.request.get(base+'/api/health');if(health.status()===200)break;if(attempt===19)throw new Error('Site did not become ready');await new Promise(r=>setTimeout(r,500));}const endpoint=base+'/api/users/'+ids[1]+'/follow';
 assert.equal((await guest.request.post(endpoint,{data:{following:true}})).status(),401);assert.equal((await ctx.request.post('http://127.0.0.1:3020/api/users/'+ids[1]+'/follow',{data:{following:true},headers:{origin:'https://untrusted.invalid',cookie:'__Host-pm_session='+tokens[0]}})).status(),403);assert.equal((await ctx.request.post(base+'/api/users/'+ids[0]+'/follow',{data:{following:true}})).status(),400);assert.equal((await ctx.request.post(endpoint,{data:{following:'yes'}})).status(),400);
 const results=await Promise.all(Array.from({length:8},()=>ctx.request.post(endpoint,{data:{following:true}})));assert(results.every(r=>r.status()===200));assert.equal((await pool.query('select count(*)::int n from user_follows where follower_id=$1 and following_id=$2',ids)).rows[0].n,1);console.log('PASS authentication, origin, self-follow, bool validation and concurrent idempotent subscription');
 const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const bob='qa_bob_'+suffix;
 await page.goto(base+'/tr/u/'+bob);assert.equal(await page.locator('[data-testid=subscriber-count]').textContent(),'1 abone');await page.getByRole('button',{name:'Abonelikten çık',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-testid=subscriber-count]')?.textContent==='0 abone');await page.getByRole('button',{name:'Abone ol',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-testid=subscriber-count]')?.textContent==='1 abone');console.log('PASS subscriber button, count refresh and unsubscribe on ordinary player profile');
 await page.goto(base+'/tr/me/community?tab=following');await page.getByRole('heading',{name:'Follows QA Bob',exact:true}).waitFor();assert.equal((await pool.query('select count(*)::int n from subscriptions where user_id=any($1)',[ids])).rows[0].n,0);assert.equal((await pool.query('select count(*)::int n from payments where user_id=any($1)',[ids])).rows[0].n,0);console.log('PASS social lists persist without paid plan or payment records');
 for(const width of [375,768,1440]){await page.setViewportSize({width,height:950});for(const route of ['/tr','/tr/people','/tr/u/'+bob,'/tr/me/community','/tr/me']){await page.goto(base+route);assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),route+' overflow '+width);}await page.screenshot({path:`test-results/community/profile-${width}.png`,fullPage:true});}
 await page.setViewportSize({width:375,height:812});await page.goto(base+'/tr/games?sort=new#catalog');await page.locator('.language-trigger').tap();await page.locator('.language-options button[lang=az]').tap();await page.waitForURL(/\/az\/games\?sort=new#catalog/);assert.equal(await page.locator('html').getAttribute('lang'),'az');await page.reload();assert.equal(await page.locator('html').getAttribute('lang'),'az');console.log('PASS real touch locale selection, query/hash and reload persistence');
 const fonts=await page.evaluate(()=>({body:getComputedStyle(document.body).fontFamily,weight:getComputedStyle(document.body).fontWeight,logo:getComputedStyle(document.querySelector('.logo-wordmark')).fontFamily,preloads:document.querySelectorAll('link[rel=preload][as=font]').length,mode:document.compatMode}));assert(fonts.body.includes('Montserrat'));assert(Number(fonts.weight)>=600);assert(fonts.logo.includes('Montserrat'));assert.equal(fonts.preloads,0);assert.equal(fonts.mode,'CSS1Compat');console.log('PASS self-hosted Montserrat, semibold body/logo, no unused font preloads and Standards Mode');
 assert.equal(errors.length,0,errors.join('\n'));
 await browser.close();browser=null;
 const ff=await firefox.launch({headless:true});browser=ff;const fctx=await ff.newContext({viewport:{width:375,height:812},hasTouch:true}),fp=await fctx.newPage();await fp.goto(base+'/tr/games?sort=new');await fp.locator('.language-trigger').tap();await fp.locator('.language-options button[lang=en]').tap();await fp.waitForURL(/\/en\/games\?sort=new/);await fp.waitForFunction(()=>document.documentElement.lang==='en' && document.querySelector('.language-trigger')?.getAttribute('aria-label')?.includes('EN'));assert.equal(await fp.locator('html').getAttribute('lang'),'en');console.log('PASS Firefox mobile-sized touch language change');
 }finally{await browser?.close();await pool.query('delete from users where id=any($1)',[ids]);await pool.end();}
})().catch(e=>{console.error(e);process.exitCode=1});
