/** Reviewed SWF additions; one identical runtime bundle and one editorial curator per game. */
import {populateCurators} from './populate-curators';
import fs from 'node:fs/promises';import {readFileSync} from 'node:fs';import path from 'node:path';import {eq,sql} from 'drizzle-orm';import {db,schema} from '../src/lib/db';import {paths,env} from '../src/lib/env';import {newId} from '../src/lib/ids';import {createVersion,approveVersion} from '../src/lib/versions';import {createSwfWrapper,RUFFLE_PUBLIC_PATH,RUFFLE_VERSION} from '../src/lib/legacy-flash';import {packRuntime,scanVersion} from '../src/lib/virustotal';import {archiveHash} from '../src/lib/archive-hash';import {scanAllowsApproval} from '../src/lib/virustotal-result';
type Item={slug:string;title:string;category:string;repo:string;revision:string;file:string;sourceSha:string;sha256:string;bytes:number};
const prepared=process.env.PLAYMINT_SWF_PREPARED||'';const records=JSON.parse(readFileSync('catalogue/legacy-additions.json','utf8')) as Item[];
async function rows(){return db.select({game:schema.games,version:schema.gameVersions}).from(schema.games).innerJoin(schema.gameVersions,eq(schema.gameVersions.gameId,schema.games.id)).where(sql`${schema.games.slug} in (${sql.join(records.map(r=>sql`${r.slug}`),sql`, `)}) and ${schema.gameVersions.number}=(select max(v.number) from game_versions v where v.game_id=${schema.games.id})`);}
async function stage(){if(!prepared)throw Error('prepared_required');const root=path.join(prepared,'bundle');await fs.mkdir(root,{recursive:true});await fs.writeFile(path.join(root,'index.html'),'<!DOCTYPE html><title>Reviewed SWF collection</title>');for(const r of records){const dir=path.join(root,r.slug);await fs.mkdir(dir,{recursive:true});const src=path.join(prepared,'files',r.slug,'game.swf');if(await archiveHash(src)!==r.sha256)throw Error('source_hash_mismatch');await fs.copyFile(src,path.join(dir,'game.swf'));await fs.writeFile(path.join(dir,'index.html'),createSwfWrapper({swfFile:'game.swf',title:r.title,ruffleBaseUrl:env.siteUrl+RUFFLE_PUBLIC_PATH}));}
const archive=path.join(prepared,'bundle.zip');await packRuntime(root,archive);for(const r of records){let g=(await db.select().from(schema.games).where(eq(schema.games.slug,r.slug)))[0];if(g?.liveVersionId){const live=(await db.select().from(schema.gameVersions).where(eq(schema.gameVersions.id,g.liveVersionId)))[0];if(live?.report.legacyFlash?.sourceSha!==r.sourceSha)throw Error('slug_owned_by_another_game:'+r.slug);continue;}if(!g){const id=newId();const description={en:`${r.title} is a classic Flash game played with Ruffle. Original game credits are retained. Archive source: https://github.com/${r.repo}/blob/${r.revision}/${encodeURIComponent(r.file)}`,tr:`${r.title}, Ruffle ile tarayıcıda oynanan klasik bir Flash oyunudur. Orijinal oyun künyesi korunur. Arşiv kaynağı: https://github.com/${r.repo}/blob/${r.revision}/${encodeURIComponent(r.file)}`,az:`${r.title}, Ruffle ilə brauzerdə oynanan klassik Flash oyunudur. Orijinal oyun müəlliflərinin məlumatı qorunur. Arxiv mənbəyi: https://github.com/${r.repo}/blob/${r.revision}/${encodeURIComponent(r.file)}`};await db.insert(schema.games).values({id,developerId:'vwh477h4esdtyzjsceeg',slug:r.slug,title:r.title,description,tagline:{en:'Classic Flash collection',tr:'Klasik Flash koleksiyonu',az:'Klassik Flash kolleksiyası'},category:r.category,license:'Developer',tags:['legacy-flash','curated-flash'],mobileResponsive:false,fullscreenSupported:true,orientation:'landscape',isDemo:false});g=(await db.select().from(schema.games).where(eq(schema.games.id,id)))[0];}
let v=(await db.select().from(schema.gameVersions).where(eq(schema.gameVersions.gameId,g.id)))[0];if(!v){const id=await createVersion(g.id,{archivePath:archive,size:(await fs.stat(archive)).size},'Curated SWF addition; original credits retained.',100);v=(await db.select().from(schema.gameVersions).where(eq(schema.gameVersions.id,id)))[0];}const stamp=new Date('2026-10-07T00:00:00Z');for(const f of v.files)await fs.utimes(path.join(v.filesDir,f.path),stamp,stamp);await db.update(schema.gameVersions).set({entry:r.slug+'/index.html',report:{...v.report,entry:r.slug+'/index.html',legacyFlash:{sourceType:'github-swf',sourceRepository:'https://github.com/'+r.repo,sourceFile:r.file,sourceFiles:[r.file],sourceSha:r.sourceSha,sha256:r.sha256,rightsStatus:'operator_authorized',technicalStatus:'pending',ruffleVersion:RUFFLE_VERSION,runtimeStatus:'untested',importedAt:new Date().toISOString(),swfBytes:r.bytes}}}).where(eq(schema.gameVersions.id,v.id));console.log('staged',r.slug,v.id);}}
async function scan(){const v=(await rows()).find(r=>r.version.status==='pending')?.version;if(v){await scanVersion(v.id);const current=(await db.select().from(schema.gameVersions).where(eq(schema.gameVersions.id,v.id)))[0];console.log(JSON.stringify(current.report.virustotal));}}
async function publish(){const all=await rows();if(all.length!==records.length)throw Error('all_staged_required');const clean=all.find(r=>scanAllowsApproval(r.version.report.virustotal));if(!clean)throw Error('real_clean_scan_required');const admin=(await db.select().from(schema.users).where(eq(schema.users.role,'admin'))).find(u=>!u.banned);if(!admin)throw Error('admin_required');for(const {version:v} of all){if(v.status!=='pending')continue;if(v.report.legacyFlash?.runtimeStatus!=='ok')throw Error('runtime_not_reviewed');const file=path.join(paths.scans(),v.id+'-verify.zip');await packRuntime(v.filesDir,file);if(await archiveHash(file)!==clean.version.report.virustotal!.sha256)throw Error('scan_hash_mismatch');await fs.rm(file,{force:true});await fs.stat(path.join(prepared,'covers',v.id+'.png'));}
for(const {game:g,version:v} of all){if(v.status!=='pending')continue;const src=path.join(prepared,'covers',v.id+'.png'),cover=g.id+'-'+(await archiveHash(src)).slice(0,12)+'.png';await fs.copyFile(src,path.join(paths.covers(),cover));await db.update(schema.games).set({coverPath:cover}).where(eq(schema.games.id,g.id));await db.update(schema.gameVersions).set({report:{...v.report,legacyFlash:{...v.report.legacyFlash!,technicalStatus:'approved'},virustotal:clean.version.report.virustotal,sharedScanVersionId:clean.version.id}}).where(eq(schema.gameVersions.id,v.id));await approveVersion(v.id,admin.id,'Operator-requested catalogue addition; Ruffle runtime checked and identical bundle SHA-256 verified against actual clean VirusTotal analysis. Original game credits retained.');console.log('published',g.slug);}
await populateCurators(all.map(r=>r.game.id));}
void(async()=>{if(process.argv[2]==='stage')await stage();else if(process.argv[2]==='scan')await scan();else if(process.argv[2]==='publish')await publish();else console.log(JSON.stringify((await rows()).map(r=>({slug:r.game.slug,version:r.version.id,scan:r.version.report.virustotal?.status})),null,2));process.exit(0)})().catch(e=>{console.error(e);process.exit(1)});
