/** Each mobile game must pass its own actual runtime scan and browser review. */
import fs from 'node:fs/promises';import path from 'node:path';import {readFileSync} from 'node:fs';import {eq,sql} from 'drizzle-orm';
import {db,schema} from '../src/lib/db';import {paths} from '../src/lib/env';import {newId} from '../src/lib/ids';import {createVersion,approveVersion} from '../src/lib/versions';import {scanVersion,packRuntime} from '../src/lib/virustotal';import {scanAllowsApproval} from '../src/lib/virustotal-result';import {archiveHash} from '../src/lib/archive-hash';import {populateCurators} from './populate-curators';
type Item={key:string;slug:string;title:string;category:string;repo:string;revision:string;runtimeRevision?:string;author:string;license:string;orientation:string;tagline:schema.I18nText};
const records=JSON.parse(readFileSync('catalogue/mobile/manifest.json','utf8')) as Item[],prepared=path.resolve(process.env.PLAYMINT_MOBILE_PREPARED||'work/mobile-games');
async function rows(){return db.select({game:schema.games,version:schema.gameVersions}).from(schema.games).innerJoin(schema.gameVersions,eq(schema.games.id,schema.gameVersions.gameId)).where(sql`${schema.games.slug} in (${sql.join(records.map(r=>sql`${r.slug}`),sql`, `)}) and ${schema.gameVersions.number}=(select max(v.number) from game_versions v where v.game_id=${schema.games.id})`);}
async function stage(){const reviewer=(await db.select().from(schema.users).where(eq(schema.users.role,'admin'))).find(u=>!u.banned);if(!reviewer)throw Error('admin_required');
 for(const r of records){let g=(await db.select().from(schema.games).where(eq(schema.games.slug,r.slug)))[0];if(g){const v=(await db.select().from(schema.gameVersions).where(eq(schema.gameVersions.gameId,g.id)))[0];if(v?.report.openSource?.repository!=='https://github.com/'+r.repo)throw Error('slug_owned_elsewhere');if(process.argv[3]!==r.key){console.log('already_staged',r.slug);continue;}}
  const id=g?.id||newId(),source=`https://github.com/${r.repo}/tree/${r.revision}`,description={en:`${r.tagline.en}\n\nOriginal developer: ${r.author}. MIT licence. Source: ${source}\nTouch controls and fullscreen supported.`,tr:`${r.tagline.tr}\n\nOrijinal geliştirici: ${r.author}. MIT lisansı. Kaynak: ${source}\nDokunmatik kontrol ve tam ekran desteklenir.`,az:`${r.tagline.az}\n\nOrijinal müəllif: ${r.author}. MIT lisenziyası. Mənbə: ${source}\nToxunma idarələri və tam ekran dəstəklənir.`};
  if(!g)await db.insert(schema.games).values({id,developerId:reviewer.id,slug:r.slug,title:r.title,category:r.category,tagline:r.tagline,description,license:r.license,tags:['open-source','mobile','curated-mobile'],mobileResponsive:true,fullscreenSupported:true,orientation:r.orientation,isDemo:false});
  const archive=path.join(prepared,r.key+'.zip'),vId=await createVersion(id,{archivePath:archive,size:(await fs.stat(archive)).size},'Reviewed mobile collection; original authors and MIT licence preserved.',30);
  const v=(await db.select().from(schema.gameVersions).where(eq(schema.gameVersions.id,vId)))[0];await db.update(schema.gameVersions).set({report:{...v.report,openSource:{author:r.author,repository:'https://github.com/'+r.repo,source,revision:r.revision,license:r.license,licensePath:'LICENSE',adaptations:['isolated saves','viewport fixes',...(r.key==='jewelsback'?['optional external audio/art omitted; runtime '+r.runtimeRevision]:[]) ]}}}).where(eq(schema.gameVersions.id,vId));console.log('staged',r.slug,vId);
 }
}
async function scan(){for(const {version:v} of await rows())if(!scanAllowsApproval(v.report.virustotal)){await scanVersion(v.id);break;}}
async function publish(){const all=await rows(),reviewer=(await db.select().from(schema.users).where(eq(schema.users.role,'admin'))).find(u=>!u.banned);if(!reviewer||all.length!==records.length)throw Error('staged_review_required');
 for(const {game:g,version:v} of all){if(v.status==='approved')continue;if(!scanAllowsApproval(v.report.virustotal))throw Error('clean_scan_required:'+g.slug);const r=records.find(r=>r.slug===g.slug)!,review=JSON.parse(await fs.readFile(path.join(prepared,'reviews',r.key+'.json'),'utf8'));if(review.version!==v.id||review.runtimeSha256!==v.report.virustotal?.sha256||!review.mobile||!review.desktop||!review.touch)throw Error('browser_review_required');const check=path.join(prepared,r.key+'-verify.zip');try{await packRuntime(v.filesDir,check);if(await archiveHash(check)!==review.runtimeSha256)throw Error('runtime_changed_since_review');}finally{await fs.rm(check,{force:true});}await fs.stat(path.join(prepared,'covers',r.key+'.png'));}
 for(const {game:g,version:v} of all){if(v.status==='approved')continue;const r=records.find(r=>r.slug===g.slug)!,src=path.join(prepared,'covers',r.key+'.png'),cover=g.id+'-'+(await archiveHash(src)).slice(0,12)+'.png';await fs.mkdir(paths.covers(),{recursive:true});await fs.copyFile(src,path.join(paths.covers(),cover));await db.update(schema.games).set({coverPath:cover}).where(eq(schema.games.id,g.id));await approveVersion(v.id,reviewer.id,'Operator-requested mobile catalogue addition. Original MIT authors retained; desktop and touch gameplay reviewed. Actual per-game VirusTotal scan completed.');console.log('published',g.slug);}
 await populateCurators(all.map(r=>r.game.id));
}
void(async()=>{const mode=process.argv[2];if(mode==='stage')await stage();else if(mode==='scan')await scan();else if(mode==='publish')await publish();else{console.log(JSON.stringify((await rows()).map(r=>({slug:r.game.slug,version:r.version.id,filesDir:r.version.filesDir,entry:r.version.entry,scan:r.version.report.virustotal})),null,2));}process.exit(0)})().catch(e=>{console.error(e);process.exit(1)});
