/** Operator-selected archive additions. Scan a private bundle; publish only byte-identical reviewed members. */
import fs from 'node:fs/promises';import path from 'node:path';import {readFileSync} from 'node:fs';import {eq} from 'drizzle-orm';import {db,schema} from '../src/lib/db';import {paths,env} from '../src/lib/env';import {newId} from '../src/lib/ids';import {createSwfWrapper,RUFFLE_PUBLIC_PATH,RUFFLE_VERSION} from '../src/lib/legacy-flash';import {createVersion,approveVersion} from '../src/lib/versions';import {packRuntime,scanVersion} from '../src/lib/virustotal';import {archiveHash} from '../src/lib/archive-hash';import {scanAllowsApproval} from '../src/lib/virustotal-result';import {populateCurators} from './populate-curators';
type Item={slug:string;title:string;category:string;repo:string;revision:string;file:string;sourceSha:string;sha256:string;bytes:number;sourceUrl:string};
const records=JSON.parse(readFileSync('catalogue/linked-swf/manifest.json','utf8')) as Item[],prepared=path.resolve(process.env.PLAYMINT_LINKED_PREPARED||'work/linked-swf'),bundleSlug='internal-linked-swf-scan-20261008';
async function admin(){const u=(await db.select().from(schema.users).where(eq(schema.users.role,'admin'))).find(u=>!u.banned);if(!u)throw Error('admin_required');return u;}
async function bundle(){return (await db.select({game:schema.games,version:schema.gameVersions}).from(schema.games).innerJoin(schema.gameVersions,eq(schema.games.id,schema.gameVersions.gameId)).where(eq(schema.games.slug,bundleSlug)))[0];}
async function stage(){if(await bundle()){console.log('bundle_already_staged');return;}const root=path.join(prepared,'bundle');await fs.mkdir(root,{recursive:true});await fs.writeFile(path.join(root,'index.html'),'<!doctype html><title>Private archive review</title>');
 for(const r of records){if(!/^[a-z0-9-]+$/.test(r.slug))throw Error('invalid_member');const dir=path.join(root,r.slug);await fs.mkdir(dir,{recursive:true});const src=path.join(prepared,'files',r.slug,'game.swf');if(await archiveHash(src)!==r.sha256)throw Error('source_hash_mismatch');await fs.copyFile(src,path.join(dir,'game.swf'));await fs.writeFile(path.join(dir,'index.html'),createSwfWrapper({swfFile:'game.swf',title:r.title,ruffleBaseUrl:env.siteUrl+RUFFLE_PUBLIC_PATH}));await fs.writeFile(path.join(dir,'CREDITS.txt'),`${r.title}\nOriginal game credits and copyright remain in the SWF. Playmint curators manage the listing, not authorship.\nArchive source: ${r.sourceUrl}\nRevision: ${r.revision}\nThe archive repository's licence does not establish an open-source licence for the original game.\n`);}
 const archive=path.join(prepared,'bundle.zip');await packRuntime(root,archive);const u=await admin(),id=newId();await db.insert(schema.games).values({id,developerId:u.id,slug:bundleSlug,title:'Private linked archive scan bundle',category:'arcade',license:'Developer',status:'unlisted',isDemo:false});const version=await createVersion(id,{archivePath:archive,size:(await fs.stat(archive)).size},'Private operator-selected archive review; not a public game.',160);console.log('bundle_staged',version);
}
async function scan(){const b=await bundle();if(!b)throw Error('bundle_required');await scanVersion(b.version.id);}
async function publish(){const b=await bundle();if(!b||!scanAllowsApproval(b.version.report.virustotal))throw Error('real_clean_bundle_scan_required');const u=await admin();const reviews=JSON.parse(await fs.readFile(path.join(prepared,'reviews.json'),'utf8')) as {slug:string;playable:boolean;notes:string}[];const accepted=records.filter(r=>reviews.some(v=>v.slug===r.slug&&v.playable));if(!accepted.length)throw Error('playable_review_required');const check=path.join(prepared,'bundle-check.zip');try{await packRuntime(b.version.filesDir,check);if(await archiveHash(check)!==b.version.report.virustotal!.sha256)throw Error('scanned_bundle_changed');}finally{await fs.rm(check,{force:true});}const gameIds:string[]=[];
 for(const r of accepted){await fs.stat(path.join(prepared,'covers',r.slug+'.png'));const dir=path.join(b.version.filesDir,r.slug);if(await archiveHash(path.join(dir,'game.swf'))!==r.sha256)throw Error('member_changed');}
 for(const r of accepted){let g=(await db.select().from(schema.games).where(eq(schema.games.slug,r.slug)))[0];if(g?.liveVersionId){const live=(await db.select().from(schema.gameVersions).where(eq(schema.gameVersions.id,g.liveVersionId)))[0];if(live?.report.legacyFlash?.sha256!==r.sha256)throw Error('slug_owned_elsewhere');gameIds.push(g.id);continue;}
  if(!g){const id=newId(),description={en:`${r.title}, played with Ruffle. Original author credits and copyright remain in the game. Archive source: ${r.sourceUrl}\nDesktop controls; fullscreen supported.`,tr:`${r.title}, Ruffle ile oynanır. Orijinal geliştirici künyesi ve telif bildirimleri oyunda korunur. Arşiv kaynağı: ${r.sourceUrl}\nBilgisayar kontrolleri; tam ekran desteklenir.`,az:`${r.title}, Ruffle ilə oynanır. Orijinal müəllif məlumatı və müəllif hüququ bildirişləri oyunda qorunur. Arxiv mənbəyi: ${r.sourceUrl}\nKompüter idarələri; tam ekran dəstəklənir.`};await db.insert(schema.games).values({id,developerId:u.id,slug:r.slug,title:r.title,category:r.category,description,tagline:{en:'Classic Flash collection',tr:'Klasik Flash koleksiyonu',az:'Klassik Flash kolleksiyası'},license:'Developer',tags:['legacy-flash','curated-flash'],mobileResponsive:false,fullscreenSupported:true,orientation:'landscape',isDemo:false});g=(await db.select().from(schema.games).where(eq(schema.games.id,id)))[0];}
  const member=path.join(b.version.filesDir,r.slug),archive=path.join(prepared,r.slug+'.zip');await packRuntime(member,archive);const id=await createVersion(g.id,{archivePath:archive,size:(await fs.stat(archive)).size},'Operator-selected archive addition; original game credits retained.',60);const v=(await db.select().from(schema.gameVersions).where(eq(schema.gameVersions.id,id)))[0];
  const expected=['index.html','game.swf','CREDITS.txt'];if(v.files.length!==expected.length)throw Error('unexpected_member_files');for(const name of expected)if(await archiveHash(path.join(v.filesDir,name))!==await archiveHash(path.join(member,name)))throw Error('scan_member_changed');
  const review=reviews.find(x=>x.slug===r.slug)!,coverSource=path.join(prepared,'covers',r.slug+'.png'),cover=g.id+'-'+(await archiveHash(coverSource)).slice(0,12)+'.png';await fs.mkdir(paths.covers(),{recursive:true});await fs.copyFile(coverSource,path.join(paths.covers(),cover));await db.update(schema.games).set({coverPath:cover}).where(eq(schema.games.id,g.id));
  const meta={sourceType:r.repo==='MaxGames'?'publisher-swf' as const:'github-swf' as const,sourceRepository:r.repo==='MaxGames'?'https://www.maxgames.com/':'https://github.com/'+r.repo,sourceFile:r.file,sourceFiles:[r.file],sourceSha:r.sourceSha,sha256:r.sha256,rightsStatus:'operator_authorized' as const,technicalStatus:'approved' as const,ruffleVersion:RUFFLE_VERSION,runtimeStatus:'ok' as const,importedAt:new Date().toISOString(),swfBytes:r.bytes};
  await db.update(schema.gameVersions).set({report:{...v.report,legacyFlash:meta,virustotal:b.version.report.virustotal,sharedScanVersionId:b.version.id,scanScope:{kind:'bundle-member',member:r.slug,bundleSha256:b.version.report.virustotal!.sha256}}}).where(eq(schema.gameVersions.id,id));await approveVersion(id,u.id,'Explicit operator publication request. Original copyright retained. Actual clean VirusTotal bundle scan; every runtime member hash verified. Browser review: '+review.notes);gameIds.push(g.id);console.log('published',r.title);
 }
 await populateCurators(gameIds);await fs.rm(b.version.filesDir,{recursive:true,force:true});if(b.version.projectDir)await fs.rm(b.version.projectDir,{recursive:true,force:true});await fs.rm(b.version.sourceZipPath,{force:true});await db.delete(schema.games).where(eq(schema.games.id,b.game.id));await fs.rm(path.join(prepared,'bundle.zip'),{force:true});for(const r of records)await fs.rm(path.join(prepared,r.slug+'.zip'),{force:true});console.log('private_bundle_removed');
}
void(async()=>{const mode=process.argv[2];if(mode==='stage')await stage();else if(mode==='scan')await scan();else if(mode==='publish')await publish();else{const b=await bundle();console.log(JSON.stringify(b?{version:b.version.id,scan:b.version.report.virustotal}:null));}process.exit(0)})().catch(e=>{console.error(e);process.exit(1)});
