/** Explicit operator-requested publication; exact runtime members scanned as one bundle. */
import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';import {eq,sql} from 'drizzle-orm';import {db,schema} from '../src/lib/db';import {paths} from '../src/lib/env';import {newId} from '../src/lib/ids';import {createVersion,approveVersion} from '../src/lib/versions';import {packRuntime,scanVersion} from '../src/lib/virustotal';import {scanAllowsApproval} from '../src/lib/virustotal-result';import {audit} from '../src/lib/audit';
const owner='vwh477h4esdtyzjsceeg',slug='internal-legacy-scan-bundle',root=path.join(paths.scans(),'legacy-batch-runtime');
async function items(){return db.select({game:schema.games,version:schema.gameVersions}).from(schema.games).innerJoin(schema.gameVersions,eq(schema.gameVersions.gameId,schema.games.id)).where(sql`${schema.gameVersions.report} ? 'legacyFlash'`);}
async function bundle(){return (await db.select({game:schema.games,version:schema.gameVersions}).from(schema.games).innerJoin(schema.gameVersions,eq(schema.gameVersions.gameId,schema.games.id)).where(eq(schema.games.slug,slug)))[0];}
async function hash(file:string){return createHash('sha256').update(await fs.readFile(file)).digest('hex');}
async function stage(){if(await bundle())return;await fs.mkdir(root,{recursive:true});await fs.writeFile(path.join(root,'index.html'),'<!DOCTYPE html><title>Private legacy review bundle</title>');const all=await items();if(all.length!==24)throw Error('expected_24_existing_swf_games');
for(const {version:v} of all){if(v.report.legacyFlash?.runtimeStatus!=='ok')throw Error('runtime_not_tested:'+v.id);await fs.cp(v.filesDir,path.join(root,v.id),{recursive:true});}
const archive=path.join(paths.scans(),'legacy-collection.zip');await packRuntime(root,archive);const prior=(await db.select().from(schema.games).where(eq(schema.games.slug,slug)))[0];const id=prior?.id||newId();if(!prior)await db.insert(schema.games).values({id,developerId:owner,slug,title:'Private legacy scan bundle',category:'arcade',license:'Developer',status:'unlisted',isDemo:false});await createVersion(id,{archivePath:archive,size:(await fs.stat(archive)).size},'Private combined scan; not a playable catalogue game.',300);console.log('staged',id);}
async function scan(){const b=await bundle();if(!b)throw Error('bundle_required');await scanVersion(b.version.id);const v=(await db.select().from(schema.gameVersions).where(eq(schema.gameVersions.id,b.version.id)))[0];console.log(JSON.stringify(v.report.virustotal));}
async function publish(){const b=await bundle();if(!b||!scanAllowsApproval(b.version.report.virustotal))throw Error('real_clean_batch_scan_required');const admin=(await db.select().from(schema.users).where(eq(schema.users.role,'admin'))).find(u=>!u.banned);if(!admin)throw Error('admin_required');const all=await items();
// A clean bundle result applies only to byte-identical members, never arbitrary uploads.
for(const {version:v} of all)for(const f of v.files)if(await hash(path.join(v.filesDir,f.path))!==await hash(path.join(b.version.filesDir,v.id,f.path)))throw Error('scan_member_changed:'+v.id+':'+f.path);
for(const {game:g,version:v} of all){if(v.status==='approved')continue;const meta=v.report.legacyFlash!;if(meta.runtimeStatus!=='ok')throw Error('runtime_failed');const cover=g.id+'-'+(await hash(path.join(paths.scans(),'legacy-covers',v.id+'.png'))).slice(0,12)+'.png';await fs.copyFile(path.join(paths.scans(),'legacy-covers',v.id+'.png'),path.join(paths.covers(),cover));await db.update(schema.games).set({developerId:owner,coverPath:cover}).where(eq(schema.games.id,g.id));await db.update(schema.gameVersions).set({report:{...v.report,legacyFlash:{...meta,rightsStatus:'operator_authorized',technicalStatus:'approved'},virustotal:b.version.report.virustotal,sharedScanVersionId:b.version.id,scanScope:{kind:'bundle-member',member:v.id,bundleSha256:b.version.report.virustotal!.sha256}} as schema.ScanReport}).where(eq(schema.gameVersions.id,v.id));await audit(admin.id,'legacy.operator_authorized',g.id,{instruction:'User explicitly requested public embedding of existing VPS SWF games',sourceSha:meta.sourceSha});await approveVersion(v.id,admin.id,'Explicit platform operator publication request. Ruffle reviewed; all runtime bytes verified against the clean VirusTotal bundle. Original game credits retained.');console.log('published',g.slug);}
await fs.rm(root,{recursive:true,force:true});await fs.rm(path.join(paths.scans(),'legacy-collection.zip'),{force:true});await fs.rm(b.version.filesDir,{recursive:true,force:true});if(b.version.projectDir)await fs.rm(b.version.projectDir,{recursive:true,force:true});await fs.rm(b.version.sourceZipPath,{force:true});await db.delete(schema.games).where(eq(schema.games.id,b.game.id));}
void(async()=>{if(process.argv[2]==='stage')await stage();else if(process.argv[2]==='scan')await scan();else if(process.argv[2]==='publish')await publish();process.exit(0)})().catch(e=>{console.error(e);process.exit(1)});
