/* Uses only temporary accounts and private uploads. No financial operations. */
const {Pool}=require('pg'),{chromium}=require('@playwright/test'),crypto=require('crypto'),fs=require('fs/promises'),path=require('path'),assert=require('assert');
const pool=new Pool({connectionString:process.env.DATABASE_URL}),id='qa-redesign-'+Date.now(),token=crypto.randomBytes(32).toString('base64url'),base=process.env.PLAYMINT_TEST_ORIGIN||'https://playmint.tr',out=process.env.PLAYMINT_QA_OUTPUT||'test-results/redesign';let browser;
(async()=>{try{
 await fs.mkdir(out,{recursive:true});await pool.query("insert into users(id,email,name,password_hash,role) values($1,$2,'Redesign QA','disabled','admin')",[id,id+'@qa.invalid']);await pool.query("insert into developer_profiles(user_id,handle,display_name) values($1,$2,'Redesign QA')",[id,id]);await pool.query('insert into sessions(id,user_id,expires_at) values($1,$2,now()+interval \'1 hour\')',[crypto.createHash('sha256').update(token).digest('hex'),id]);
 browser=await chromium.launch({headless:true,...(process.env.PLAYMINT_CHROMIUM_PATH?{executablePath:process.env.PLAYMINT_CHROMIUM_PATH,args:['--no-sandbox']}:{} )});const ctx=await browser.newContext();await ctx.addCookies([{name:'__Host-pm_session',value:token,domain:new URL(base).hostname,path:'/',secure:true,httpOnly:true,sameSite:'Lax'}]);const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const admin='/tr/studio-bcb7017af2212dfd4eb0e12ee757edc05d2234d4';const live=(await pool.query("select slug from games where status='published' and not is_demo order by published_at desc limit 1")).rows[0];
 if(process.env.PLAYMINT_QA_WORKFLOW_ONLY!=="true"){
 for(const width of [375,768,1440])for(const [name,route] of [['home','/tr'],['catalog','/tr/games'],['game','/tr/g/'+live.slug],['studio','/tr/dev'],['upload','/tr/dev/games/new'],['admin',admin+'/review']]){
  await page.setViewportSize({width,height:1000});const res=await page.goto(base+route);await page.evaluate(()=>document.fonts.ready);assert(res.status()<400,route+' '+res.status());assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),name+' overflow at '+width);await page.screenshot({path:path.join(out,`${name}-${width}.png`),fullPage:true});console.log('PASS responsive '+name+' '+width);
 }
 if(process.env.PLAYMINT_QA_CAPTURE_ONLY==='true')return;
 for(const width of [375,768,1440]){await page.setViewportSize({width,height:1000});for(const route of ['/dev/games','/dev/analytics','/dev/subscriptions','/dev/subscribers','/dev/ads','/dev/earnings','/dev/settings','/dev/account','/dev/sdk','/me','/me/library','/me/settings','/me/subscriptions']){await page.goto(base+'/tr'+route);assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),route+' overflow '+width);}for(const route of ['/users','/games','/finance','/ads','/settings','/requests']){await page.goto(base+admin+route);assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),route+' overflow '+width);}console.log('PASS all Studio/account/admin pages '+width);}
 }
 await page.goto(base+'/en/report');await page.locator('#contact-email').fill(id+'@qa.invalid');await page.locator('#contact-message').fill('QA integration message: please ignore; removed after verification.');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.getByRole('status').waitFor();const report=(await pool.query("select id from audit_log where actor_id=$1 and action='platform.report' order by id desc limit 1",[id])).rows[0];assert(report,'Contact form did not persist');await page.goto(base+admin+'/requests');const card=page.locator('article').filter({hasText:id+'@qa.invalid'});await card.getByRole('button',{name:'Çözüldü olarak işaretle',exact:true}).click();await card.getByText('Çözüldü',{exact:true}).waitFor();assert.equal((await pool.query('select data from audit_log where id=$1',[report.id])).rows[0].data.status,'resolved');console.log('PASS contact is persisted, scoped to admin and can be resolved');
 let uploadStarts=0;page.on('request',r=>{if(new URL(r.url()).pathname==='/api/uploads'&&r.method()==='POST')uploadStarts++;});await page.goto(base+'/tr/dev/games/new');await page.locator('#title').fill('Private redesign QA');await page.locator('#category').selectOption('puzzle');await page.locator('select[name=mobileResponsive]').selectOption('yes');await page.locator('select[name=fullscreenSupported]').selectOption('yes');await page.getByRole('button',{name:'Devam et',exact:true}).click();await page.locator('input[name=cover]').setInputFiles(path.resolve('public/brand/logo.png'));await page.locator('input[name=zip]').setInputFiles(path.resolve('tests/fixtures/vite-project.zip'));await page.getByRole('button',{name:'Devam et',exact:true}).click();await page.waitForTimeout(300);assert.equal(uploadStarts,0,'Continue submitted the archive before review');assert(await page.getByRole('button',{name:'Oyunu yükle',exact:true}).isEnabled());await page.getByRole('button',{name:'Oyunu yükle',exact:true}).click();await page.waitForURL(/\/dev\/games\/[a-z0-9]{20}$/,{timeout:120000});const game=(await pool.query('select * from games where developer_id=$1',[id])).rows[0],version=(await pool.query('select * from game_versions where game_id=$1',[game.id])).rows[0];assert.equal(game.status,'draft');assert.equal(version.status,'pending');assert.equal(game.category,'puzzle');assert.equal(game.mobile_responsive,true);assert.equal(game.fullscreen_supported,true);console.log('PASS wizard creates a private pending version with capability metadata');
 await page.goto(base+'/tr/dev/subscriptions');const plan=page.locator('form').filter({has:page.locator('input[name=gameId]')}).first();await plan.locator('input[name=price]').fill('22.90');await plan.locator('select[name=currency]').selectOption('TRY');await plan.locator('button[type=submit]').click();await page.getByRole('status').waitFor();const offer=(await pool.query('select subscription_currency,subscription_price_cents from games where id=$1',[game.id])).rows[0];assert.equal(offer.subscription_currency,'TRY');assert.equal(offer.subscription_price_cents,2290);await page.goto(base+'/tr/dev/ads');const ads=page.locator('form').filter({has:page.locator('input[name=gameId]')}).first();await ads.locator('input[name=enabled]').check();await ads.locator('select[name=intervalSeconds]').selectOption('600');await ads.getByRole('button',{name:'Ayarları kaydet',exact:true}).click();await page.waitForURL(/saved=1/);const config=(await pool.query('select * from game_ad_settings where game_id=$1',[game.id])).rows[0];assert.equal(config.enabled,true);assert.equal(config.interval_seconds,600);const publicConfig=await (await ctx.request.get(base+'/api/ads/config?gameId='+game.id)).json();assert.equal(publicConfig.enabled,false);assert.equal((await pool.query('select count(*)::int n from payments where user_id=$1',[id])).rows[0].n,0);console.log('PASS TRY plan and ad settings persist; no charge or live ad enabled for an unapproved game');
 for(const language of ['az','en']){await page.setViewportSize({width:375,height:1000});for(const route of ['/dev','/dev/ads','/dev/earnings','/dev/sdk','/dev/subscriptions','/dev/notifications','/me/settings']){await page.goto(base+'/'+language+route);assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),language+route+' overflow');}console.log('PASS localized Studio and account pages '+language);}
 await page.setViewportSize({width:375,height:812});await page.goto(base+'/tr/g/'+game.slug+'?preview='+version.id);await page.getByRole('button',{name:'Oyna',exact:true}).click();const frame=page.locator('iframe[title=game]');await frame.waitFor();await frame.evaluate(el=>el.dataset.qaPreserve='yes');await page.getByRole('button',{name:'Tam ekrandan çık',exact:true}).click();assert.equal(await page.locator('.is-immersive').count(),0);assert.equal(await frame.getAttribute('data-qa-preserve'),'yes');assert.notEqual(await page.evaluate(()=>document.body.style.overflow),'hidden');console.log('PASS real private game starts and exits mobile immersive without resetting its iframe');assert.equal(errors.length,0,errors.join('\n'));
 }finally{
 const versions=(await pool.query('select v.* from game_versions v join games g on g.id=v.game_id where g.developer_id=$1',[id])).rows,covers=(await pool.query('select cover_path from games where developer_id=$1',[id])).rows;await pool.query('delete from audit_log where actor_id=$1',[id]);await pool.query('delete from users where id=$1',[id]);for(const v of versions)for(const f of [v.source_zip_path,v.files_dir,v.project_dir,'/var/lib/playmint/scans/'+v.id+'.zip'])if(f?.startsWith('/var/lib/playmint/'))await fs.rm(f,{recursive:true,force:true});for(const c of covers)if(c.cover_path)await fs.rm('/var/lib/playmint/covers/'+c.cover_path,{force:true});for(const folder of await fs.readdir('/var/lib/playmint/uploads')){try{const record=JSON.parse(await fs.readFile('/var/lib/playmint/uploads/'+folder+'/state.json'));if(record.owner===id)await fs.rm('/var/lib/playmint/uploads/'+folder,{recursive:true,force:true});}catch{}}await browser?.close();await pool.end();
 }
})().catch(e=>{console.error(e);process.exitCode=1});
