import {UploadWizard} from "@/components/UploadWizard";
import {CoverPicker} from '@/components/CoverPicker';
import {UploadPolicy} from '@/components/UploadPolicy';
import {GameCapabilities} from '@/components/GameCapabilities';
import {resolveLocale} from '@/lib/i18n';
import {requireDeveloper} from '@/lib/auth';
import {getSettings} from '@/lib/settings';
import {uploadLabels} from '@/lib/i18n/forms';
import {UploadForm} from '@/components/UploadForm';
import {SimpleZipPicker} from '@/components/SimpleZipPicker';
import {StudioHeading} from '@/components/Studio';
import {categories} from '@/lib/catalog';
export default async function NewGame({params}:PageProps<'/[locale]/dev/games/new'>){const {locale,t}=await resolveLocale(params);await requireDeveloper(locale);const s=await getSettings(),en=locale==='en',az=locale==='az';return <div className="space-y-7"><StudioHeading eyebrow="PLAYMINT / PUBLISH" title={en?'Give your game a home':az?'Oyunun burada yer alsın':'Oyunun burada yer alsın'} description={en?'Name it, show it, tell players how to enjoy it.':az?'Adını yaz, üz qabığını seç və oyununu yüklə.':'Adını yaz, kapağını seç ve oyuncuların nasıl oynayacağını belirt.'}/><div className="upload-workspace"><div className="upload-primary"><UploadForm hideSubmit endpoint="/api/dev/games" redirectTo={`/${locale}/dev/games/{gameId}`} submitLabel={en?'Upload game':az?'Oyunu yüklə':'Oyunu yükle'} labels={uploadLabels(t)}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="simpleUpload" value="on"/><UploadWizard locale={locale} submitLabel={en?"Upload game":az?"Oyunu yüklə":"Oyunu yükle"} steps={[<div key="details" className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><div><label className="label" htmlFor="title">{en?'Game name':az?'Oyunun adı':'Oyun adı'}</label><input className="input" id="title" name="title" required maxLength={60} placeholder="Pocket Factory"/></div><div><label className="label" htmlFor="category">{en?'Category':az?'Kateqoriya':'Kategori'}</label><select className="input" id="category" name="category" required defaultValue=""><option value="" disabled>{en?'Choose a category':az?'Kateqoriya seç':'Kategori seç'}</option>{categories.map(c=><option value={c} key={c}>{t.categories[c]}</option>)}</select></div></div><GameCapabilities locale={locale} required/><div><label className="label" htmlFor="orientation">{en?'Screen orientation':az?'Ekran istiqaməti':'Ekran yönü'}</label><select className="input" id="orientation" name="orientation" defaultValue="landscape"><option value="landscape">{en?'Landscape':az?'Üfüqi':'Yatay'}</option><option value="portrait">{en?'Portrait':az?'Şaquli':'Dikey'}</option><option value="any">{en?'Both':az?'Hər ikisi':'İkisi de'}</option></select></div></div>,<div key="files" className="space-y-5"><CoverPicker locale={locale}/><SimpleZipPicker locale={locale} maxMb={s.maxZipMb}/></div>,<div key="policy"><UploadPolicy locale={locale}/></div>]}/></UploadForm></div><aside className="upload-note"><img src="/brand/studio.webp" alt="" width="800" height="500"/><h2>{en?'From your desk to their next favourite.':az?'Masandan oyunçularına.':'Masandan oyuncularına.'}</h2><p>{en?'Upload the full project ZIP. A ready dist/build is picked automatically. Every version is reviewed before release.':az?'Layihənin ZIP faylını yüklə. Hazır dist/build avtomatik seçilir. Hər versiya yoxlanılır.':'Projenin ZIP dosyasını yükle. Hazır dist/build otomatik seçilir. Her sürüm yayınlanmadan önce incelenir.'}</p></aside></div></div>;}
