import {resolveLocale} from '@/lib/i18n';
import {requireDeveloper} from '@/lib/auth';
import {StudioHeading} from '@/components/Studio';
export default async function Docs({params}:PageProps<'/[locale]/dev/sdk'>){const {locale}=await resolveLocale(params);await requireDeveloper(locale);const en=locale==='en';return <div className="space-y-6"><StudioHeading eyebrow="PLAYMINT / SDK" title={en?'Ads in a few lines':'Birkaç satırda reklam'} description={en?'Playmint supplies the SDK to approved builds. Only connect your game lifecycle and optional reward button.':'Playmint onaylı oyun çıktısına SDK’yı ekler. Sadece oyunun durdur/devam et işlevlerini ve isteğe bağlı ödül butonunu bağla.'}/><section className="card space-y-4 p-6"><h2 className="h2">1. {en?'Pause and resume':'Durdur ve devam et'}</h2><p className="text-sm text-muted">{en?'Connect before allowing midgame ads; pause simulation, timers and audio.':'Ara reklamlar için oyunun simülasyonunu, zamanlayıcılarını ve sesini durduracak bağlantıyı ekle.'}</p><pre className="overflow-auto rounded-xl bg-slate-900 p-5 text-sm text-white"><code>{`window.Playmint.init({
  pause: () => { game.pause(); audio.pause(); },
  resume: () => { game.resume(); audio.resume(); }
});
// Phaser: game.scene.pause('FactoryScene'); game.sound.pauseAll();
// Resume: game.scene.resume('FactoryScene'); game.sound.resumeAll();`}</code></pre></section><section className="card space-y-4 p-6"><h2 className="h2">2. {en?'Watch an ad for a reward':'Reklam izle, ödül kazan'}</h2><p className="text-sm text-muted">{en?'Show the reward and require a voluntary button click. Never grant a reward for dismissal, no-fill or failure.':'Ödülü oyuncuya göster ve isteğe bağlı bir butonla sun. İptal, reklam bulunamaması ve hata durumunda ödül verme.'}</p><pre className="overflow-auto rounded-xl bg-slate-900 p-5 text-sm text-white"><code>{`rewardButton.onclick = async () => {
  const result = await Playmint.requestReward('double_damage');
  if (result.completed) activateDoubleDamage(60);
};
// Placements: revive, extra_hp, bonus_coins, double_damage
// completed describes the game reward, never real-money earnings.`}</code></pre></section><section className="card space-y-3 p-6"><h2 className="h2">3. {en?'Testing and upload':'Test ve yükleme'}</h2><p className="text-sm text-muted">{en?'Publish a new dist ZIP and wait for review. Startup ads are automatic when enabled; game settings control ad breaks without another upload. Preview mode never earns money.':'Yeni dist ZIP’ini yükle ve incelemeyi bekle. Başlangıç reklamı etkinleştirildiğinde otomatik çalışır; reklam sıklığı ZIP’i yeniden yüklemeden panelden değiştirilir. Önizleme para kazandırmaz.'}</p><p className="text-sm text-muted">{en?'No ad, timeout or an ad blocker never stops the game. Google approval is required for live ads.':'Reklam yokluğu, zaman aşımı veya reklam engelleyici oyunu kilitlemez. Canlı reklam için Google onayı gerekir.'}</p></section><section className="card p-6"><span className="badge bg-violet-100 text-violet-700">Coming soon</span><h2 className="h2 mt-3">Gems & purchases</h2><p className="mt-2 text-sm text-muted">{en?'Purchases are unavailable. The SDK cannot charge money or create spendable currency.':'Satın alma kullanılamaz. SDK para çekemez veya harcanabilir gerçek para bakiyesi oluşturamaz.'}</p></section></div>;}
