import {num} from "@/lib/format";
import {profileById} from "@/lib/community";
import Link from "next/link";
import {resolveLocale} from "@/lib/i18n";
import {requireUser} from "@/lib/auth";
import {playerLibrary} from "@/lib/player-data";
import {GameGrid} from "@/components/GameCard";
import {StudioHeading,StudioEmpty,StudioIcon} from "@/components/Studio";
export default async function Me({params}:PageProps<"/[locale]/me">){const {locale,t}=await resolveLocale(params);const user=await requireUser(locale),en=locale==="en",az=locale==="az";const profile=await profileById(user.id,user.id);const [liked,recent]=await playerLibrary(user.id);return <div className="space-y-7"><StudioHeading eyebrow="YOUR PLAYER SPACE" title={`${en?"Welcome":az?"Xoş gəldin":"Hoş geldin"}, ${user.name}`} accent="blue" description={en?"Your favorites, your subscriptions and your next game.":az?"Sevimli oyunların, abunəliklərin və növbəti oyunun.":"Favorilerin, aboneliklerin ve bir sonraki oyunun."}/><Link className="profile-social-link" href={`/${locale}/me/community`}><strong>{num(profile?.followers??0,locale)}</strong> {en?"subscribers":az?"abunəçi":"abone"} · <strong>{num(profile?.followingCount??0,locale)}</strong> {en?"subscriptions":az?"abunəlik":"takip"}</Link><div className="grid gap-4 sm:grid-cols-2"><Link className="studio-box hover:border-mint/30" href={`/${locale}/me/library`}><StudioIcon name="game"/><h2 className="mt-4">{en?"Your game library":az?"Oyun kitabxanan":"Oyun kütüphanen"}</h2><p className="text-xs text-muted mt-2">{liked.length} {en?"favorites":az?"sevimli oyun":"favori oyun"} →</p></Link><Link className="studio-box hover:border-mint/30" href={`/${locale}/me/subscriptions`}><StudioIcon name="plan"/><h2 className="mt-4">{en?"Your game subscriptions":az?"Oyun abunəliklərin":"Oyun aboneliklerin"}</h2><p className="text-xs text-muted mt-2">{en?"Manage your game plans":az?"Oyun planlarını idarə et":"Oyun planlarını yönet"} →</p></Link></div><section><h2 className="h2 mb-5">{t.me.recent}</h2>{recent.length?<GameGrid games={recent.slice(0,6)} locale={locale} t={t}/>:<StudioEmpty title={en?"Your next favorite is waiting":az?"Növbəti sevimli oyunun səni gözləyir":"Bir sonraki favorin seni bekliyor"} text={t.me.emptyRecent} href={`/${locale}/games`} cta={en?"Discover games":az?"Oyunları kəşf et":"Oyunları keşfet"}/>}</section></div>;}
